version: '3.7'
services:
  database:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=database
    ports:
      - "5400:5432"
    volumes:
      - ./postgres-data:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    